name: Upload pod

on: [repository_dispatch]

jobs:
  build:
    name: Dockerize pod and upload with repo dispatch
    if: github.event.action == 'pod-upload'
    runs-on: ubuntu-latest
    steps:
      - name: 'Cloning user repo'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.JINA_DEV_BOT }}
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT }}
          repository: ${{ github.event.client_payload.repository }}
      - name: Jina Hub Image Builder and Push to docker hub
        uses: jina-ai/hub-builder@master        
        with:
          push: false
          dockerhub_username: ${{ secrets.JINAHUB_DOCKER_USER }}
          dockerhub_password: ${{ secrets.JINAHUB_DOCKER_PWD }}
          slack_webhook: ${{ secrets.JINAHUB_SLACK_WEBHOOK }}
